// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package datastore

import (
	"context"
)

const expungePayment = `-- name: ExpungePayment :exec
DELETE FROM Payment WHERE correlation_id = ?
`

func (q *Queries) ExpungePayment(ctx context.Context, correlationID string) error {
	_, err := q.db.ExecContext(ctx, expungePayment, correlationID)
	return err
}

const logPayment = `-- name: LogPayment :exec
INSERT INTO Payment (requested_at, correlation_id, processor, amount)
             VALUES (           ?,              ?,         ?,      ?)
`

type LogPaymentParams struct {
	RequestedAt   string
	CorrelationID string
	Processor     string
	Amount        float64
}

func (q *Queries) LogPayment(ctx context.Context, arg LogPaymentParams) error {
	_, err := q.db.ExecContext(ctx, logPayment,
		arg.RequestedAt,
		arg.CorrelationID,
		arg.Processor,
		arg.Amount,
	)
	return err
}
